package study.hry.spring.springhibernate.simple;

import java.util.Date;

/**
 * TmpEmp generated by hbm2java
 */
public class TmpEmp implements java.io.Serializable {
	private static final long serialVersionUID = 1L;
	
	private int id;
    private String name;
    private Date birthday;
    private Character sex;
    private Float salary;

    public TmpEmp() {
    }

    public TmpEmp(int id) {
        this.id = id;
    }

    public TmpEmp(int id, String name, Date birthday, Character sex,
            Float salary) {
        this.id = id;
        this.name = name;
        this.birthday = birthday;
        this.sex = sex;
        this.salary = salary;
    }

    public int getId() {
        return this.id;
    }

    public void setId(int id) {
        this.id = id;
    }

    public String getName() {
        return this.name;
    }

    public void setName(String name) {
        this.name = name;
    }

    public Date getBirthday() {
        return this.birthday;
    }

    public void setBirthday(Date birthday) {
        this.birthday = birthday;
    }

    public Character getSex() {
        return this.sex;
    }

    public void setSex(Character sex) {
        this.sex = sex;
    }

    public Float getSalary() {
        return this.salary;
    }

    public void setSalary(Float salary) {
        this.salary = salary;
    }

}
